// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ewrkziqfphcokjqqpkks.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV3cmt6aXFmcGhjb2tqcXFwa2tzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5MDgwNTYsImV4cCI6MjA1ODQ4NDA1Nn0.x4j5J6A9mcVf-s9rUxYWmR6kZyhclFGw-EjFmc_peLQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);